services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kastenliste
    ports:
      - "5432:5432"
    volumes:
      - kastenliste_dev_db:/var/lib/postgresql/data

volumes:
  kastenliste_dev_db:
